# Generated by Django 5.1.3 on 2024-11-30 19:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('standard', 'Usuario Estándar')], default='standard', max_length=10, verbose_name='Rol del usuario')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuario_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('no_propuesta', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('concepto', models.TextField(blank=True)),
                ('proyecto', models.CharField(max_length=100)),
                ('socio', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('GTQ', 'Quetzales')], max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateField()),
                ('persona_recibe', models.CharField(max_length=100)),
                ('correo_recibe', models.EmailField(max_length=254)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('solicitante', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('factura', models.CharField(blank=True, max_length=20, null=True)),
                ('autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('recibo_operado', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to='clientes.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['correlativo'], name='clientes_cl_correla_eb4668_idx'), models.Index(fields=['razon_social'], name='clientes_cl_razon_s_eb90c9_idx')],
            },
        ),
    ]
