# Generated by Django 5.1.3 on 2024-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_archivo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_impuesto',
            field=models.CharField(choices=[('AFECTO', 'Afecto'), ('EXENTO', 'Exento')], default='AFECTO', max_length=10, verbose_name='Tipo de Impuesto'),
        ),
    ]
