# Generated by Django 5.1.3 on 2024-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tipo_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_impuesto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='impuesto',
            field=models.CharField(choices=[('AFECTO', 'Afecto'), ('EXENTO', 'Exento')], default='AFECTO', max_length=10, verbose_name='Tipo de Impuesto'),
        ),
    ]
