# Generated by Django 5.1.3 on 2024-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_tipo_impuesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente',
            field=models.CharField(default='Cliente por Defecto', help_text='Nombre del cliente o empresa', max_length=200, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='autorizacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Autorización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Base Imponible'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='concepto',
            field=models.TextField(blank=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cliente',
            field=models.EmailField(max_length=254, verbose_name='Correo del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_recibe',
            field=models.EmailField(max_length=254, verbose_name='Correo de Recepción'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='encargado',
            field=models.CharField(max_length=100, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_factura',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, null=True, verbose_name='Estado de Factura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='factura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. de Factura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='impuesto',
            field=models.CharField(choices=[('AFECTO', 'Afecto (12%)'), ('EXENTO', 'No Afecto (0%)')], default='AFECTO', max_length=10, verbose_name='Tipo de Impuesto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('GTQ', 'Quetzales')], max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='no_propuesta',
            field=models.CharField(max_length=50, verbose_name='No. de Propuesta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='persona_recibe',
            field=models.CharField(max_length=100, verbose_name='Persona que Recibe'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proyecto',
            field=models.CharField(max_length=100, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='recibo_operado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recibo Operado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='socio',
            field=models.CharField(max_length=100, verbose_name='Socio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='solicitante',
            field=models.CharField(max_length=100, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='total_factura',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Factura'),
        ),
    ]
