# Generated by Django 5.1.3 on 2024-12-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options_cliente_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo del Cliente')),
                ('correo_recibe', models.EmailField(max_length=254, verbose_name='Correo de Recepción')),
                ('persona_recibe', models.CharField(max_length=100, verbose_name='Persona que Recibe')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente Base',
                'verbose_name_plural': 'Clientes Base',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['nit'], name='clientes_cl_nit_b506eb_idx'), models.Index(fields=['razon_social'], name='clientes_cl_razon_s_16530f_idx')],
            },
        ),
    ]
